language: c++
compiler: gcc
sudo: true
matrix:
  include:
  - os: linux
    env:
    - TARGET="docs"
    addons:
      apt:
        packages:
        - doxygen
        - git
  exclude:
  - compiler: gcc
install:
- if [ "$TARGET" == "android" ] || [ "$TARGET" == "linux" ] || [ "$TARGET" == "docs"
  ]; then scripts/ci/$TARGET/install.sh; fi
script:
- scripts/ci/$TARGET/build.sh $OPT
- if [ "$TARGET" == "osx" ] || [ "$TARGET" == "linux" ]; then scripts/ci/$TARGET/run_tests.sh;
  fi
after_success: if [ "$TARGET" == "docs" ]; then scripts/ci/$TARGET/after_success.sh;
  fi
git:
  depth: 10
env:
  global:
    secure: UQgO9GZfgVBD8KZpkR+StfJhg85NGOrJ1luAM5vaRZmaRrG8o9ULSEv9wGa3GjNK+kLncqymhcC3eZIN15TFcFIsYrOaYPnT1oDjOOiqXj6wJxDREwh1qf2lm/KiXkrOjH4JG5h2sW0ELJe+iEFX1AzNJtEHpe/tHAVYrILCwc0=
